### ISSUE TITLE
Bug: Comments with leading whitespace break parsing

### ISSUE THREAD

**Issue by rehlma** [onepub-dev/pubspec_manager#17]
When using the `pubspec_manager` package to parse a `pubspec.yaml` file, I encountered an unexpected parsing error when placing a comment with leading whitespace under a dependency key.

### Example
```yaml
environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ^3.22.3

dependencies:
  # A comment with leading whitespace works correctly here.
  provider:
    # But a comment with leading whitespace does not get parsed correctly here.
    # path: ../provider
    hosted:
      url: https://pub.dartlang.org
      version: ^6.1.4
  pubspec_manager:
# However, if there's no leading whitespace before the comment, it works fine.
# path: ../pubspec_manager
    hosted:
      url: https://pub.dartlang.org
      version: ^1.0.1
```

### Error
```sh
Unhandled exception:
Pubspec: /path/packages/package/pubspec.yaml
Line No.: 13 
Line Type: comment
Section Indent: 2 
Line Content:     # A comment with leading whitespace does not get parsed correctly here.
Error: Line 13 is not a key so you cannot extract a value: Line No: 13 Type: comment     # But a comment with leading whitespace does not get parsed correctly here.
#0      LineImpl.keyValue (package:pubspec_manager/src/document/line_impl.dart:140)
#1      Document.findKeyChild (package:pubspec_manager/src/document/document.dart:116)
#2      LineImpl.findKeyChild (package:pubspec_manager/src/document/line_impl.dart:178)
#3      LineImpl.findRequiredKeyChild (package:pubspec_manager/src/document/line_impl.dart:187)
#4      new DependencyAltHosted._fromLine (package:pubspec_manager/src/pubspec/dependency_alt_hosted.dart:24)
#5      new Dependency._loadFrom (package:pubspec_manager/src/pubspec/dependency.dart:37)
#6      PubSpec._initDependencies (package:pubspec_manager/src/pubspec/pubspec.dart:211)
#7      new PubSpec._loadFromDocument (package:pubspec_manager/src/pubspec/pubspec.dart:63)
#8      new PubSpec.load (package:pubspec_manager/src/pubspec/pubspec.dart:109)
#9      new PubSpec.loadFromPath (package:pubspec_manager/src/pubspec/pubspec.dart:120)
```

### Expected Behavior
Comments inside dependency blocks should not affect parsing, regardless of whether they are indented or not. YAML itself allows for indented comments, so this seems to be a parser-specific issue.
