### ISSUE TITLE
 Unexpected child key found sdk

### ISSUE THREAD

**Issue by laterdayi** [onepub-dev/pubspec_manager#2]
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  bot_toast: ^4.1.3
  get: ^4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  easy_refresh: ^3.3.3+1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  logger: ^2.0.2+1
  open_filex: ^4.3.4
  android_id: ^0.3.6
```
